# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# Sửa phần production ở đây
production:
  <<: *default # Kế thừa pool và timeout từ default nếu muốn
  adapter: postgresql # Đổi sang postgresql
  encoding: unicode
  # Không cần các dòng database, username, password, host riêng lẻ
  # Render sẽ cung cấp toàn bộ qua DATABASE_URL
  url: <%= ENV['DATABASE_URL'] %>
